name: Build Edirom Online Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - dev-ewk
  pull_request:
    branches:
      - dev-ewk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre git

      - name: Copy Sencha CMD Dockerfile
        run: |
          git clone --depth 1 https://github.com/bwbohl/sencha-cmd.git /tmp/sencha-cmd
          cp /tmp/sencha-cmd/Dockerfile ${{ github.workspace }}/Dockerfile

      - name: Build Docker Image
        run: |
          docker build -f ${{ github.workspace }}/Dockerfile -t edirom-online-build .
        working-directory: ${{ github.workspace }}

      - name: Run Build in Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app edirom-online-build "./build.sh production"

      - name: Upload XAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: eof-ewk
          path: build-xar/*.xar
  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download XAR Artifact
          uses: actions/download-artifact@v4
          with:
            name: eof-ewk

        - name: Rename XAR file
          run: |
            mv Edirom-Online-Frontend*.xar eof-ewk-latest.xar
        - name: Get Release by Tag
          id: get_release
          uses: actions/github-script@v6
          with:
            script: |
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'latest'
              });
              return release.data.upload_url;

        - name: Echo Upload URL
          run: echo "Upload URL:"${{ steps.get_release.outputs.upload_url }}"'

        - name: Upload XAR to Release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./eof-ewk-latest.xar
            asset_name: eof-ewk-latest.xar
            asset_content_type: application/octet-stream