name: Build Edirom Online Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - dev-ewk
  pull_request:
    branches:
      - dev-ewk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre git

      - name: Copy Sencha CMD Dockerfile
        run: |
          git clone --depth 1 https://github.com/bwbohl/sencha-cmd.git /tmp/sencha-cmd
          cp /tmp/sencha-cmd/Dockerfile ${{ github.workspace }}/Dockerfile

      - name: Build Docker Image
        run: |
          docker build -f ${{ github.workspace }}/Dockerfile -t edirom-online-build .
        working-directory: ${{ github.workspace }}

      - name: Run Build in Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app edirom-online-build "./build.sh production"

      - name: Upload XAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: edirom-online-frontend-xar
          path: build-xar/*.xar
  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download XAR Artifact
          uses: actions/download-artifact@v4
          with:
            name: edirom-online-frontend-xar

        - name: Delete old latest tag
          run: |
            git push --delete origin latest || true
            git tag -d latest || true

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: latest
            release_name: Release latest
            draft: false
            prerelease: false

        - name: Upload XAR to Release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: edirom-online-frontend-xar/edirom-online-frontend-xar.xar
            asset_name: edirom-online-frontend-ewk_latest.xar
            asset_content_type: application/octet-stream