name: Build and Release EWK Frontend

on:
  push:
    branches:
      - dev-ewk
    tags:
      - "v*"
      - "release-*"

env:
  IMAGE_NAME_GHCR: ghcr.io/korngold-werkausgabe/eof-ewk:latest
  IMAGE_NAME_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/eof-ewk:latest

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      # ------------- Docker Registries Login & Buildx Setup ----------
      - name: Login to GitHub Packages Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ------------ Docker Image Build & Push (multiarch) ----------
      - name: Build and push multiarch image
        env:
          IMAGE_NAME_GHCR: ghcr.io/korngold-werkausgabe/eof-ewk:latest
          IMAGE_NAME_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/eof-ewk:latest
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f docker/Dockerfile \
            -t $IMAGE_NAME_GHCR \
            -t $IMAGE_NAME_DOCKERHUB \
            --push .

      # ---------------- Optional: Build-Artifact ---------------
      - name: Create eof-ewk-latest.tar.gz
        run: tar -czf eof-ewk-latest.tar.gz build

      - name: Upload eof-ewk-latest.tar.gz as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eof-ewk-latest.tar.gz
          path: eof-ewk-latest.tar.gz

      - name: Upload eof-ewk-latest.tar.gz as Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: eof-ewk-latest.tar.gz