name: Build and Release EWK Frontend

on:
  push:
    branches:
      - dev-ewk
      - trigger-ewk-actions
    tags:
      - "v*"
      - "release-*"

env:
  IMAGE_NAME_GHCR: ghcr.io/korngold-werkausgabe/eof-ewk:latest
  IMAGE_NAME_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/eof-ewk:latest

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      # ------------- Docker Registries Login & Buildx Setup ----------
      - name: Login to GitHub Packages Docker
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # ------------ Docker Image Build & Push (multiarch) ----------
      - name: Build and push multiarch image
        env:
          IMAGE_NAME_GHCR: ghcr.io/korngold-werkausgabe/eof-ewk:latest
          IMAGE_NAME_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/eof-ewk:latest
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f docker/Dockerfile \
            -t $IMAGE_NAME_GHCR \
            -t $IMAGE_NAME_DOCKERHUB \
            --push .