name: Release XAR

on:
  workflow_run:
    workflows: ["Build Edirom Online Frontend"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download XAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: edirom-online-frontend-xar

      - name: Delete old latest tag
        run: |
          git push --delete origin latest || true
          git tag -d latest || true

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release latest
          draft: false
          prerelease: false

      - name: Upload XAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-xar/edirom-online-frontend-xar.xar
          asset_name: edirom-online-frontend-ewk_latest.xar
          asset_content_type: application/octet-stream
